codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 10%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "node_modules"
  - "test"
  - "scripts"
  - "artifacts"
  - "cache"
  - "coverage"
  - "dist"
  - "types"
  - "*.config.js"
  - "*.test.js"

flags:
  unittests-node-18:
    paths:
      - contracts/
    carryforward: true

  unittests-node-20:
    paths:
      - contracts/
    carryforward: true
